export type StorageType = "shelf" | "fridge" | "freezer" | "none";
export type Rarity = "common" | "rare" | "legendary";

export interface FoodItem {
  id: string;
  name: string;
  emoji: string;
  rarity: Rarity;
  cost: number;
  storage: StorageType;
  expiresIn: number | null;
  isAlcohol: boolean;
  alcoholContent: number;
  stats: {
    hunger: number;
    happiness: number;
    health: number;
    energy: number;
    cleanliness: number;
  };
}

export const FOOD_DATA: FoodItem[] = [
  {
    id: "grapes",
    name: "Grapes",
    emoji: "🍇",
    rarity: "common",
    cost: 3,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 5, health: 15, energy: 3, cleanliness: 0 },
  },
  {
    id: "melon",
    name: "Melon",
    emoji: "🍈",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -25, happiness: 8, health: 12, energy: 5, cleanliness: 0 },
  },
  {
    id: "watermelon",
    name: "Watermelon",
    emoji: "🍉",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -30, happiness: 10, health: 10, energy: 8, cleanliness: 2 },
  },
  {
    id: "orange",
    name: "Orange",
    emoji: "🍊",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 5, health: 20, energy: 5, cleanliness: 0 },
  },
  {
    id: "lemon",
    name: "Lemon",
    emoji: "🍋",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 21,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -5, happiness: -5, health: 10, energy: 2, cleanliness: 0 },
  },
  {
    id: "banana",
    name: "Banana",
    emoji: "🍌",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 8, health: 8, energy: 15, cleanliness: 0 },
  },
  {
    id: "pineapple",
    name: "Pineapple",
    emoji: "🍍",
    rarity: "common",
    cost: 4,
    storage: "shelf",
    expiresIn: 10,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -25, happiness: 10, health: 15, energy: 8, cleanliness: 1 },
  },
  {
    id: "mango",
    name: "Mango",
    emoji: "🥭",
    rarity: "rare",
    cost: 3,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 12, health: 18, energy: 10, cleanliness: 0 },
  },
  {
    id: "red_apple",
    name: "Red Apple",
    emoji: "🍎",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 6, health: 18, energy: 5, cleanliness: 0 },
  },
  {
    id: "green_apple",
    name: "Green Apple",
    emoji: "🍏",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 5, health: 20, energy: 4, cleanliness: 0 },
  },
  {
    id: "pear",
    name: "Pear",
    emoji: "🍐",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 10,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 6, health: 16, energy: 6, cleanliness: 0 },
  },
  {
    id: "peach",
    name: "Peach",
    emoji: "🍑",
    rarity: "common",
    cost: 3,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 9, health: 14, energy: 7, cleanliness: 0 },
  },
  {
    id: "cherries",
    name: "Cherries",
    emoji: "🍒",
    rarity: "rare",
    cost: 5,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 15, health: 12, energy: 8, cleanliness: 0 },
  },
  {
    id: "strawberry",
    name: "Strawberry",
    emoji: "🍓",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 12, health: 16, energy: 6, cleanliness: 0 },
  },
  {
    id: "blueberries",
    name: "Blueberries",
    emoji: "🫐",
    rarity: "rare",
    cost: 5,
    storage: "fridge",
    expiresIn: 4,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 10, health: 22, energy: 7, cleanliness: 0 },
  },
  {
    id: "kiwi",
    name: "Kiwi",
    emoji: "🥝",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 7, health: 19, energy: 6, cleanliness: 0 },
  },
  {
    id: "tomato",
    name: "Tomato",
    emoji: "🍅",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 10,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 2, health: 14, energy: 3, cleanliness: 0 },
  },
  {
    id: "olive",
    name: "Olive",
    emoji: "🫒",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -10, happiness: 3, health: 8, energy: 2, cleanliness: 0 },
  },
  {
    id: "coconut",
    name: "Coconut",
    emoji: "🥥",
    rarity: "rare",
    cost: 4,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 8, health: 12, energy: 10, cleanliness: 0 },
  },
  {
    id: "mushroom",
    name: "Mushroom",
    emoji: "🍄",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 4, health: 10, energy: 5, cleanliness: 0 },
  },
  {
    id: "avocado",
    name: "Avocado",
    emoji: "🥑",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 6, health: 16, energy: 8, cleanliness: 0 },
  },
  {
    id: "eggplant",
    name: "Eggplant",
    emoji: "🍆",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 10,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 2, health: 9, energy: 3, cleanliness: 0 },
  },
  {
    id: "potato",
    name: "Potato",
    emoji: "🥔",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -25, happiness: 3, health: 8, energy: 12, cleanliness: 0 },
  },
  {
    id: "carrot",
    name: "Carrot",
    emoji: "🥕",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 21,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 3, health: 18, energy: 4, cleanliness: 0 },
  },
  {
    id: "corn",
    name: "Corn",
    emoji: "🌽",
    rarity: "common",
    cost: 2,
    storage: "freezer",
    expiresIn: 90,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 5, health: 10, energy: 10, cleanliness: 0 },
  },
  {
    id: "hot_pepper",
    name: "Hot Pepper",
    emoji: "🌶️",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: -3, health: 5, energy: 8, cleanliness: 0 },
  },
  {
    id: "bell_pepper",
    name: "Bell Pepper",
    emoji: "🫑",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 10,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 4, health: 15, energy: 5, cleanliness: 0 },
  },
  {
    id: "cucumber",
    name: "Cucumber",
    emoji: "🥒",
    rarity: "common",
    cost: 1,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 2, health: 8, energy: 3, cleanliness: 1 },
  },
  {
    id: "leafy_green",
    name: "Leafy Green",
    emoji: "🥬",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -10, happiness: 2, health: 16, energy: 4, cleanliness: 0 },
  },
  {
    id: "broccoli",
    name: "Broccoli",
    emoji: "🥦",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -15, happiness: 1, health: 20, energy: 5, cleanliness: 0 },
  },
  {
    id: "garlic",
    name: "Garlic",
    emoji: "🧄",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: -2, health: 12, energy: 3, cleanliness: -2 },
  },
  {
    id: "onion",
    name: "Onion",
    emoji: "🧅",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 0, health: 10, energy: 4, cleanliness: -1 },
  },
  {
    id: "peanuts",
    name: "Peanuts",
    emoji: "🥜",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 180,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 6, health: 12, energy: 14, cleanliness: 0 },
  },
  {
    id: "legumes",
    name: "Legumes",
    emoji: "🫘",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 3, health: 14, energy: 12, cleanliness: 0 },
  },
  {
    id: "chestnut",
    name: "Chestnut",
    emoji: "🌰",
    rarity: "rare",
    cost: 4,
    storage: "shelf",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 7, health: 13, energy: 11, cleanliness: 0 },
  },
  {
    id: "bread",
    name: "Bread",
    emoji: "🍞",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -30, happiness: 4, health: 6, energy: 10, cleanliness: 0 },
  },
  {
    id: "croissant",
    name: "Croissant",
    emoji: "🥐",
    rarity: "common",
    cost: 4,
    storage: "shelf",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 10, health: 4, energy: 8, cleanliness: 0 },
  },
  {
    id: "baguette",
    name: "Baguette",
    emoji: "🥖",
    rarity: "common",
    cost: 4,
    storage: "shelf",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -35, happiness: 5, health: 5, energy: 12, cleanliness: 0 },
  },
  {
    id: "pretzel",
    name: "Pretzel",
    emoji: "🥨",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 6, health: 3, energy: 8, cleanliness: 0 },
  },
  {
    id: "bagel",
    name: "Bagel",
    emoji: "🥯",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -25, happiness: 7, health: 5, energy: 10, cleanliness: 0 },
  },
  {
    id: "pancakes",
    name: "Pancakes",
    emoji: "🥞",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 12, health: 6, energy: 12, cleanliness: 0 },
  },
  {
    id: "waffle",
    name: "Waffle",
    emoji: "🧇",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -25, happiness: 11, health: 5, energy: 11, cleanliness: 0 },
  },
  {
    id: "cheese",
    name: "Cheese",
    emoji: "🧀",
    rarity: "common",
    cost: 6,
    storage: "fridge",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 8, health: 10, energy: 8, cleanliness: 0 },
  },
  {
    id: "meat_on_bone",
    name: "Meat on Bone",
    emoji: "🍖",
    rarity: "common",
    cost: 12,
    storage: "freezer",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -35, happiness: 10, health: 18, energy: 15, cleanliness: -1 },
  },
  {
    id: "poultry_leg",
    name: "Poultry Leg",
    emoji: "🍗",
    rarity: "common",
    cost: 8,
    storage: "freezer",
    expiresIn: 45,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -30, happiness: 9, health: 16, energy: 13, cleanliness: -1 },
  },
  {
    id: "cut_of_meat",
    name: "Cut of Meat",
    emoji: "🥩",
    rarity: "common",
    cost: 10,
    storage: "freezer",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -32, happiness: 8, health: 20, energy: 14, cleanliness: -1 },
  },
  {
    id: "bacon",
    name: "Bacon",
    emoji: "🥓",
    rarity: "common",
    cost: 7,
    storage: "freezer",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 12, health: 8, energy: 12, cleanliness: -2 },
  },
  {
    id: "hamburger",
    name: "Hamburger",
    emoji: "🍔",
    rarity: "common",
    cost: 8,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 14, health: 4, energy: 10, cleanliness: -1 },
  },
  {
    id: "fries",
    name: "Fries",
    emoji: "🍟",
    rarity: "common",
    cost: 4,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 10, health: 2, energy: 8, cleanliness: -1 },
  },
  {
    id: "pizza",
    name: "Pizza",
    emoji: "🍕",
    rarity: "common",
    cost: 12,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -35, happiness: 16, health: 5, energy: 12, cleanliness: -1 },
  },
  {
    id: "hot_dog",
    name: "Hot Dog",
    emoji: "🌭",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 11, health: 3, energy: 9, cleanliness: -1 },
  },
  {
    id: "sandwich",
    name: "Sandwich",
    emoji: "🥪",
    rarity: "common",
    cost: 7,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -26, happiness: 12, health: 6, energy: 10, cleanliness: -1 },
  },
  {
    id: "taco",
    name: "Taco",
    emoji: "🌮",
    rarity: "common",
    cost: 4,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 11, health: 5, energy: 9, cleanliness: -1 },
  },
  {
    id: "burrito",
    name: "Burrito",
    emoji: "🌯",
    rarity: "common",
    cost: 6,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 13, health: 6, energy: 11, cleanliness: -1 },
  },
  {
    id: "stuffed_flatbread",
    name: "Stuffed Flatbread",
    emoji: "🫔",
    rarity: "common",
    cost: 5,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -24, happiness: 12, health: 6, energy: 10, cleanliness: -1 },
  },
  {
    id: "falafel",
    name: "Falafel",
    emoji: "🧆",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 9, health: 12, energy: 10, cleanliness: 0 },
  },
  {
    id: "egg",
    name: "Egg",
    emoji: "🥚",
    rarity: "common",
    cost: 1,
    storage: "fridge",
    expiresIn: 21,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 3, health: 14, energy: 8, cleanliness: 0 },
  },
  {
    id: "cooking",
    name: "Cooking",
    emoji: "🍳",
    rarity: "common",
    cost: 6,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 10, health: 12, energy: 10, cleanliness: 0 },
  },
  {
    id: "pot_of_food",
    name: "Pot of Food",
    emoji: "🍲",
    rarity: "common",
    cost: 8,
    storage: "fridge",
    expiresIn: 4,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -32, happiness: 11, health: 14, energy: 12, cleanliness: 0 },
  },
  {
    id: "cauldron",
    name: "Cauldron",
    emoji: "🫕",
    rarity: "rare",
    cost: 15,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -40, happiness: 14, health: 16, energy: 14, cleanliness: 0 },
  },
  {
    id: "bowl_with_spoon",
    name: "Bowl with Spoon",
    emoji: "🥣",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 7, health: 10, energy: 9, cleanliness: 0 },
  },
  {
    id: "green_salad",
    name: "Green Salad",
    emoji: "🥗",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 5, health: 18, energy: 6, cleanliness: 1 },
  },
  {
    id: "popcorn",
    name: "Popcorn",
    emoji: "🍿",
    rarity: "common",
    cost: 4,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 9, health: 2, energy: 6, cleanliness: 0 },
  },
  {
    id: "butter",
    name: "Butter",
    emoji: "🧈",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: 4, health: 2, energy: 6, cleanliness: 0 },
  },
  {
    id: "salt",
    name: "Salt",
    emoji: "🧂",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -2, happiness: 0, health: 0, energy: 0, cleanliness: 0 },
  },
  {
    id: "canned_food",
    name: "Canned Food",
    emoji: "🥫",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -24, happiness: 4, health: 8, energy: 10, cleanliness: 0 },
  },
  {
    id: "bento_box",
    name: "Bento Box",
    emoji: "🍱",
    rarity: "rare",
    cost: 10,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -30, happiness: 14, health: 14, energy: 12, cleanliness: 0 },
  },
  {
    id: "rice_cracker",
    name: "Rice Cracker",
    emoji: "🍘",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 4, health: 6, energy: 7, cleanliness: 0 },
  },
  {
    id: "rice_ball",
    name: "Rice Ball",
    emoji: "🍙",
    rarity: "common",
    cost: 3,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 6, health: 8, energy: 10, cleanliness: 0 },
  },
  {
    id: "cooked_rice",
    name: "Cooked Rice",
    emoji: "🍚",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 4, health: 8, energy: 11, cleanliness: 0 },
  },
  {
    id: "curry_rice",
    name: "Curry Rice",
    emoji: "🍛",
    rarity: "common",
    cost: 6,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 10, health: 10, energy: 12, cleanliness: -1 },
  },
  {
    id: "spaghetti",
    name: "Spaghetti",
    emoji: "🍝",
    rarity: "common",
    cost: 5,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -26, happiness: 11, health: 8, energy: 12, cleanliness: -1 },
  },
  {
    id: "roasted_sweet_potato",
    name: "Roasted Sweet Potato",
    emoji: "🍠",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -24, happiness: 8, health: 12, energy: 11, cleanliness: 0 },
  },
  {
    id: "sushi",
    name: "Sushi",
    emoji: "🍣",
    rarity: "rare",
    cost: 12,
    storage: "fridge",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -26, happiness: 15, health: 16, energy: 10, cleanliness: 1 },
  },
  {
    id: "shrimp",
    name: "Shrimp",
    emoji: "🍤",
    rarity: "rare",
    cost: 10,
    storage: "freezer",
    expiresIn: 45,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 12, health: 18, energy: 11, cleanliness: 0 },
  },
  {
    id: "fish_cake",
    name: "Fish Cake",
    emoji: "🍥",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 5,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 8, health: 14, energy: 9, cleanliness: 0 },
  },
  {
    id: "fortune_cookie",
    name: "Fortune Cookie",
    emoji: "🥠",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -10, happiness: 8, health: 3, energy: 5, cleanliness: 0 },
  },
  {
    id: "fried_shrimp",
    name: "Fried Shrimp",
    emoji: "🍢",
    rarity: "rare",
    cost: 8,
    storage: "fridge",
    expiresIn: 2,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 13, health: 12, energy: 10, cleanliness: -1 },
  },
  {
    id: "crab",
    name: "Crab",
    emoji: "🦀",
    rarity: "legendary",
    cost: 20,
    storage: "freezer",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 18, health: 22, energy: 14, cleanliness: 0 },
  },
  {
    id: "lobster",
    name: "Lobster",
    emoji: "🦞",
    rarity: "legendary",
    cost: 25,
    storage: "freezer",
    expiresIn: 60,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -30, happiness: 20, health: 24, energy: 15, cleanliness: 0 },
  },
  {
    id: "shrimp_2",
    name: "Shrimp",
    emoji: "🦐",
    rarity: "rare",
    cost: 10,
    storage: "freezer",
    expiresIn: 45,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -20, happiness: 12, health: 18, energy: 11, cleanliness: 0 },
  },
  {
    id: "squid",
    name: "Squid",
    emoji: "🦑",
    rarity: "rare",
    cost: 12,
    storage: "freezer",
    expiresIn: 45,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -22, happiness: 11, health: 16, energy: 12, cleanliness: 0 },
  },
  {
    id: "oyster",
    name: "Oyster",
    emoji: "🦪",
    rarity: "legendary",
    cost: 15,
    storage: "freezer",
    expiresIn: 30,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 16, health: 20, energy: 12, cleanliness: 0 },
  },
  {
    id: "soft_ice_cream",
    name: "Soft Ice Cream",
    emoji: "🍦",
    rarity: "common",
    cost: 4,
    storage: "freezer",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 14, health: 2, energy: 6, cleanliness: 0 },
  },
  {
    id: "shaved_ice",
    name: "Shaved Ice",
    emoji: "🍧",
    rarity: "common",
    cost: 3,
    storage: "freezer",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 10, health: 1, energy: 4, cleanliness: 0 },
  },
  {
    id: "ice_cream",
    name: "Ice Cream",
    emoji: "🍨",
    rarity: "common",
    cost: 5,
    storage: "freezer",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 16, health: 3, energy: 7, cleanliness: 0 },
  },
  {
    id: "doughnut",
    name: "Doughnut",
    emoji: "🍩",
    rarity: "common",
    cost: 3,
    storage: "shelf",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 12, health: 2, energy: 8, cleanliness: 0 },
  },
  {
    id: "cookie",
    name: "Cookie",
    emoji: "🍪",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 14,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 11, health: 2, energy: 7, cleanliness: 0 },
  },
  {
    id: "birthday_cake",
    name: "Birthday Cake",
    emoji: "🎂",
    rarity: "rare",
    cost: 20,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -28, happiness: 20, health: 4, energy: 10, cleanliness: 0 },
  },
  {
    id: "cake",
    name: "Cake",
    emoji: "🍰",
    rarity: "common",
    cost: 8,
    storage: "fridge",
    expiresIn: 4,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -24, happiness: 16, health: 4, energy: 10, cleanliness: 0 },
  },
  {
    id: "cupcake",
    name: "Cupcake",
    emoji: "🧁",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 13, health: 2, energy: 8, cleanliness: 0 },
  },
  {
    id: "pie",
    name: "Pie",
    emoji: "🥧",
    rarity: "common",
    cost: 8,
    storage: "fridge",
    expiresIn: 4,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -26, happiness: 14, health: 5, energy: 11, cleanliness: 0 },
  },
  {
    id: "chocolate_bar",
    name: "Chocolate Bar",
    emoji: "🍫",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 15, health: 3, energy: 8, cleanliness: 0 },
  },
  {
    id: "candy",
    name: "Candy",
    emoji: "🍬",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: 14, health: 1, energy: 6, cleanliness: 0 },
  },
  {
    id: "lollipop",
    name: "Lollipop",
    emoji: "🍭",
    rarity: "common",
    cost: 1,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -6, happiness: 12, health: 0, energy: 5, cleanliness: 0 },
  },
  {
    id: "custard",
    name: "Custard",
    emoji: "🍮",
    rarity: "common",
    cost: 4,
    storage: "fridge",
    expiresIn: 3,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -16, happiness: 13, health: 4, energy: 8, cleanliness: 0 },
  },
  {
    id: "honey_pot",
    name: "Honey Pot",
    emoji: "🍯",
    rarity: "rare",
    cost: 8,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 12, health: 10, energy: 10, cleanliness: 0 },
  },
  {
    id: "baby_bottle",
    name: "Baby Bottle",
    emoji: "🍼",
    rarity: "common",
    cost: 3,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -18, happiness: 8, health: 12, energy: 10, cleanliness: 0 },
  },
  {
    id: "glass_of_milk",
    name: "Glass of Milk",
    emoji: "🥛",
    rarity: "common",
    cost: 2,
    storage: "fridge",
    expiresIn: 7,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 6, health: 16, energy: 8, cleanliness: 0 },
  },
  {
    id: "coffee",
    name: "Coffee",
    emoji: "☕",
    rarity: "common",
    cost: 3,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -6, happiness: 4, health: 2, energy: 18, cleanliness: 0 },
  },
  {
    id: "teapot",
    name: "Teapot",
    emoji: "🫖",
    rarity: "common",
    cost: 4,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: 5, health: 8, energy: 12, cleanliness: 0 },
  },
  {
    id: "tea",
    name: "Tea",
    emoji: "🍵",
    rarity: "common",
    cost: 2,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -6, happiness: 4, health: 10, energy: 10, cleanliness: 0 },
  },
  {
    id: "wine",
    name: "Wine",
    emoji: "🍷",
    rarity: "rare",
    cost: 15,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: true,
    alcoholContent: 12,
    stats: { hunger: -8, happiness: 12, health: -5, energy: 4, cleanliness: 0 },
  },
  {
    id: "cocktail",
    name: "Cocktail",
    emoji: "🍸",
    rarity: "rare",
    cost: 12,
    storage: "none",
    expiresIn: 1,
    isAlcohol: true,
    alcoholContent: 15,
    stats: { hunger: -6, happiness: 14, health: -8, energy: 6, cleanliness: 0 },
  },
  {
    id: "tropical_drink",
    name: "Tropical Drink",
    emoji: "🍹",
    rarity: "rare",
    cost: 10,
    storage: "none",
    expiresIn: 1,
    isAlcohol: true,
    alcoholContent: 10,
    stats: { hunger: -10, happiness: 13, health: -4, energy: 5, cleanliness: 0 },
  },
  {
    id: "beer",
    name: "Beer",
    emoji: "🍺",
    rarity: "common",
    cost: 5,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: true,
    alcoholContent: 5,
    stats: { hunger: -8, happiness: 10, health: -3, energy: 3, cleanliness: 0 },
  },
  {
    id: "beers",
    name: "Beers",
    emoji: "🍻",
    rarity: "common",
    cost: 10,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: true,
    alcoholContent: 10,
    stats: { hunger: -12, happiness: 14, health: -6, energy: 4, cleanliness: 0 },
  },
  {
    id: "clinking_glasses",
    name: "Clinking Glasses",
    emoji: "🥂",
    rarity: "rare",
    cost: 20,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: true,
    alcoholContent: 12,
    stats: { hunger: -10, happiness: 16, health: -6, energy: 5, cleanliness: 0 },
  },
  {
    id: "tumbler_glass",
    name: "Tumbler Glass",
    emoji: "🥃",
    rarity: "common",
    cost: 4,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: 4, health: 6, energy: 6, cleanliness: 0 },
  },
  {
    id: "cup_with_straw",
    name: "Cup with Straw",
    emoji: "🥤",
    rarity: "common",
    cost: 3,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -10, happiness: 5, health: 8, energy: 7, cleanliness: 0 },
  },
  {
    id: "bubble_tea",
    name: "Bubble Tea",
    emoji: "🧋",
    rarity: "common",
    cost: 5,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -14, happiness: 12, health: 6, energy: 9, cleanliness: 0 },
  },
  {
    id: "beverage_box",
    name: "Beverage Box",
    emoji: "🧃",
    rarity: "common",
    cost: 2,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -12, happiness: 8, health: 8, energy: 8, cleanliness: 0 },
  },
  {
    id: "mate",
    name: "Mate",
    emoji: "🧉",
    rarity: "common",
    cost: 3,
    storage: "none",
    expiresIn: 1,
    isAlcohol: false,
    alcoholContent: 0,
    stats: { hunger: -8, happiness: 6, health: 10, energy: 14, cleanliness: 0 },
  },
  {
    id: "bottle",
    name: "Bottle",
    emoji: "🍾",
    rarity: "legendary",
    cost: 50,
    storage: "shelf",
    expiresIn: 365,
    isAlcohol: true,
    alcoholContent: 20,
    stats: { hunger: -12, happiness: 18, health: -10, energy: 6, cleanliness: 0 },
  },
];
