// ============================================================================
// CryptArtist Studio — AI Integration Module
// OpenAI API client for chat completions and image generation
// ============================================================================

use serde::{Deserialize, Serialize};
use serde_json::json;
use std::fs;
use std::path::Path;

// ---------------------------------------------------------------------------
// Request / Response Types
// ---------------------------------------------------------------------------

#[derive(Serialize)]
struct ChatRequest {
    model: String,
    messages: Vec<ChatMessage>,
    max_tokens: u32,
    temperature: f64,
}

#[derive(Serialize, Deserialize, Clone)]
struct ChatMessage {
    role: String,
    content: String,
}

#[derive(Deserialize)]
struct ChatResponse {
    choices: Vec<ChatChoice>,
}

#[derive(Deserialize)]
struct ChatChoice {
    message: ChatMessage,
}

#[derive(Serialize)]
struct ImageRequest {
    model: String,
    prompt: String,
    n: u32,
    size: String,
}

#[derive(Deserialize)]
struct ImageResponse {
    data: Vec<ImageData>,
}

#[derive(Deserialize)]
struct ImageData {
    url: Option<String>,
    b64_json: Option<String>,
}

// ---------------------------------------------------------------------------
// System Prompt
// ---------------------------------------------------------------------------

const SYSTEM_PROMPT: &str = "You are CryptArtist AI, an expert video editor, colorist, VFX \
    artist, and audio engineer assistant built into CryptArtist Studio. You provide concise, \
    professional advice about video editing, color grading, audio mixing, visual effects, \
    compositing, motion graphics, and content creation. Use technical terminology when \
    appropriate. Format your responses with markdown for readability.";

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/// Send a chat completion request to the OpenAI API.
pub async fn chat_completion(api_key: &str, prompt: &str) -> Result<String, String> {
    let client = reqwest::Client::new();

    let request = ChatRequest {
        model: "gpt-4o".to_string(),
        messages: vec![
            ChatMessage {
                role: "system".to_string(),
                content: SYSTEM_PROMPT.to_string(),
            },
            ChatMessage {
                role: "user".to_string(),
                content: prompt.to_string(),
            },
        ],
        max_tokens: 2048,
        temperature: 0.7,
    };

    let response = client
        .post("https://api.openai.com/v1/chat/completions")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .json(&request)
        .send()
        .await
        .map_err(|e| format!("API request failed: {}", e))?;

    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        return Err(format!("OpenAI API error ({}): {}", status, body));
    }

    let chat_response: ChatResponse = response
        .json()
        .await
        .map_err(|e| format!("Failed to parse response: {}", e))?;

    chat_response
        .choices
        .first()
        .map(|c| c.message.content.clone())
        .ok_or_else(|| "No response generated by the AI model.".to_string())
}

/// Generate an image via the OpenAI DALL-E API.
/// Returns the URL of the generated image.
pub async fn generate_image(api_key: &str, prompt: &str) -> Result<String, String> {
    let client = reqwest::Client::new();

    let request = ImageRequest {
        model: "dall-e-3".to_string(),
        prompt: prompt.to_string(),
        n: 1,
        size: "1024x1024".to_string(),
    };

    let response = client
        .post("https://api.openai.com/v1/images/generations")
        .header("Authorization", format!("Bearer {}", api_key))
        .header("Content-Type", "application/json")
        .json(&request)
        .send()
        .await
        .map_err(|e| format!("Image generation failed: {}", e))?;

    if !response.status().is_success() {
        let status = response.status();
        let body = response.text().await.unwrap_or_default();
        return Err(format!("OpenAI API error ({}): {}", status, body));
    }

    let image_response: ImageResponse = response
        .json()
        .await
        .map_err(|e| format!("Failed to parse image response: {}", e))?;

    image_response
        .data
        .first()
        .and_then(|d| d.url.clone().or_else(|| d.b64_json.clone()))
        .ok_or_else(|| "No image was generated.".to_string())
}

/// Generate TTS audio via the OpenAI Audio API.
/// Saves the resulting MP3 to `out_path`.
pub async fn generate_tts(api_key: &str, text: &str, out_path: &Path) -> Result<(), String> {
    let client = reqwest::Client::new();
    let res = client
        .post("https://api.openai.com/v1/audio/speech")
        .header("Authorization", format!("Bearer {}", api_key))
        .json(&json!({
            "model": "tts-1",
            "voice": "onyx",
            "input": text
        }))
        .send()
        .await
        .map_err(|e| e.to_string())?;

    if res.status().is_success() {
        let bytes = res.bytes().await.map_err(|e| e.to_string())?;
        fs::write(out_path, bytes).map_err(|e| e.to_string())?;
        Ok(())
    } else {
        Err(format!("TTS API Error: {}", res.status()))
    }
}
